### ISSUE TITLE
Summarize Contracts Exception

### ISSUE THREAD

**Issue by jshwvr** [kcinnick/pyredictit#3]
Nick, here's another one for you:

```
Joshuas-MacBook-Pro:predictit Joshua$ python3.6 summarize_current_contracts.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "summarize_current_contracts.py", line 6, in <module>
    pyredictit_api.list_my_contracts()
  File "/Users/Joshua/Desktop/predictit/pyredictit/pyredictit.py", line 252, in list_my_contracts
    self.get_my_contracts()
  File "/Users/Joshua/Desktop/predictit/pyredictit/pyredictit.py", line 242, in get_my_contracts
    for line in urlopen(f'https://www.predictit.org/Contract/{cid}/#data').read().splitlines():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
Joshuas-MacBook-Pro:predictit Joshua$ 

```

**Comment by jshwvr** [comment]
Same result. And no.

**Comment by kcinnick** [comment]
I've done some searching and this appears to be the most relevant result: http://stackoverflow.com/questions/24675167/ca-certificates-mac-os-x

essentially, it appears to be an issue with the way that Mac handles CA certificates.  You may find this answer in particular useful: http://stackoverflow.com/a/29727422/5266746

**Comment by jshwvr** [comment]
Interesting. Good find! I got it working using these two commands:

```
ruby -ropenssl -e "p OpenSSL::X509::DEFAULT_CERT_FILE"
export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem
```
